# Generated by Django 3.0.7 on 2023-11-25 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicaciones', '0002_auto_20231124_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestacuestionario',
            name='puntaje_total',
        ),
        migrations.AlterField(
            model_name='respuestacuestionario',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicaciones.Categoria'),
        ),
    ]
